//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistoriskAtlas.Service.ServiceReferenceBiblio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.loc.gov/zing/srw/interfaces/", ConfigurationName="ServiceReferenceBiblio.SRWPort")]
    public interface SRWPort {
        
        // CODEGEN: Generating message contract since the operation SearchRetrieveOperation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestType))]
        HistoriskAtlas.Service.ServiceReferenceBiblio.SearchRetrieveOperationResponse SearchRetrieveOperation(HistoriskAtlas.Service.ServiceReferenceBiblio.SearchRetrieveOperationRequest request);
        
        // CODEGEN: Generating message contract since the operation ScanOperation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestType))]
        HistoriskAtlas.Service.ServiceReferenceBiblio.ScanOperationResponse ScanOperation(HistoriskAtlas.Service.ServiceReferenceBiblio.ScanOperationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class searchRetrieveRequestType : requestType {
        
        private string queryField;
        
        private string startRecordField;
        
        private string maximumRecordsField;
        
        private string recordPackingField;
        
        private string recordSchemaField;
        
        private string recordXPathField;
        
        private string resultSetTTLField;
        
        private string sortKeysField;
        
        private string stylesheetField;
        
        private extraDataType extraRequestDataField;
        
        public searchRetrieveRequestType() {
            this.startRecordField = "1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string startRecord {
            get {
                return this.startRecordField;
            }
            set {
                this.startRecordField = value;
                this.RaisePropertyChanged("startRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=2)]
        public string maximumRecords {
            get {
                return this.maximumRecordsField;
            }
            set {
                this.maximumRecordsField = value;
                this.RaisePropertyChanged("maximumRecords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string recordPacking {
            get {
                return this.recordPackingField;
            }
            set {
                this.recordPackingField = value;
                this.RaisePropertyChanged("recordPacking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string recordSchema {
            get {
                return this.recordSchemaField;
            }
            set {
                this.recordSchemaField = value;
                this.RaisePropertyChanged("recordSchema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string recordXPath {
            get {
                return this.recordXPathField;
            }
            set {
                this.recordXPathField = value;
                this.RaisePropertyChanged("recordXPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=6)]
        public string resultSetTTL {
            get {
                return this.resultSetTTLField;
            }
            set {
                this.resultSetTTLField = value;
                this.RaisePropertyChanged("resultSetTTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string sortKeys {
            get {
                return this.sortKeysField;
            }
            set {
                this.sortKeysField = value;
                this.RaisePropertyChanged("sortKeys");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=8)]
        public string stylesheet {
            get {
                return this.stylesheetField;
            }
            set {
                this.stylesheetField = value;
                this.RaisePropertyChanged("stylesheet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public extraDataType extraRequestData {
            get {
                return this.extraRequestDataField;
            }
            set {
                this.extraRequestDataField = value;
                this.RaisePropertyChanged("extraRequestData");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class extraDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class termType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private string numberOfRecordsField;
        
        private string displayTermField;
        
        private termTypeWhereInList whereInListField;
        
        private bool whereInListFieldSpecified;
        
        private extraDataType extraTermDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string numberOfRecords {
            get {
                return this.numberOfRecordsField;
            }
            set {
                this.numberOfRecordsField = value;
                this.RaisePropertyChanged("numberOfRecords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string displayTerm {
            get {
                return this.displayTermField;
            }
            set {
                this.displayTermField = value;
                this.RaisePropertyChanged("displayTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public termTypeWhereInList whereInList {
            get {
                return this.whereInListField;
            }
            set {
                this.whereInListField = value;
                this.RaisePropertyChanged("whereInList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool whereInListSpecified {
            get {
                return this.whereInListFieldSpecified;
            }
            set {
                this.whereInListFieldSpecified = value;
                this.RaisePropertyChanged("whereInListSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public extraDataType extraTermData {
            get {
                return this.extraTermDataField;
            }
            set {
                this.extraTermDataField = value;
                this.RaisePropertyChanged("extraTermData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.loc.gov/zing/srw/")]
    public enum termTypeWhereInList {
        
        /// <remarks/>
        first,
        
        /// <remarks/>
        last,
        
        /// <remarks/>
        only,
        
        /// <remarks/>
        inner,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/diagnostic/")]
    public partial class diagnosticType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uriField;
        
        private string detailsField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("details");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class stringOrXmlFragment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class recordType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string recordSchemaField;
        
        private string recordPackingField;
        
        private stringOrXmlFragment recordDataField;
        
        private string recordPositionField;
        
        private extraDataType extraRecordDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string recordSchema {
            get {
                return this.recordSchemaField;
            }
            set {
                this.recordSchemaField = value;
                this.RaisePropertyChanged("recordSchema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string recordPacking {
            get {
                return this.recordPackingField;
            }
            set {
                this.recordPackingField = value;
                this.RaisePropertyChanged("recordPacking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public stringOrXmlFragment recordData {
            get {
                return this.recordDataField;
            }
            set {
                this.recordDataField = value;
                this.RaisePropertyChanged("recordData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=3)]
        public string recordPosition {
            get {
                return this.recordPositionField;
            }
            set {
                this.recordPositionField = value;
                this.RaisePropertyChanged("recordPosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public extraDataType extraRecordData {
            get {
                return this.extraRecordDataField;
            }
            set {
                this.extraRecordDataField = value;
                this.RaisePropertyChanged("extraRecordData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(explainResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(scanResponseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(searchRetrieveResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class responseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class explainResponseType : responseType {
        
        private recordType recordField;
        
        private explainRequestType echoedExplainRequestField;
        
        private diagnosticType[] diagnosticsField;
        
        private extraDataType extraResponseDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public recordType record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
                this.RaisePropertyChanged("record");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public explainRequestType echoedExplainRequest {
            get {
                return this.echoedExplainRequestField;
            }
            set {
                this.echoedExplainRequestField = value;
                this.RaisePropertyChanged("echoedExplainRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("diagnostic", Namespace="http://www.loc.gov/zing/srw/diagnostic/", IsNullable=false)]
        public diagnosticType[] diagnostics {
            get {
                return this.diagnosticsField;
            }
            set {
                this.diagnosticsField = value;
                this.RaisePropertyChanged("diagnostics");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public extraDataType extraResponseData {
            get {
                return this.extraResponseDataField;
            }
            set {
                this.extraResponseDataField = value;
                this.RaisePropertyChanged("extraResponseData");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class explainRequestType : requestType {
        
        private string recordPackingField;
        
        private string stylesheetField;
        
        private extraDataType extraRequestDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string recordPacking {
            get {
                return this.recordPackingField;
            }
            set {
                this.recordPackingField = value;
                this.RaisePropertyChanged("recordPacking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string stylesheet {
            get {
                return this.stylesheetField;
            }
            set {
                this.stylesheetField = value;
                this.RaisePropertyChanged("stylesheet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public extraDataType extraRequestData {
            get {
                return this.extraRequestDataField;
            }
            set {
                this.extraRequestDataField = value;
                this.RaisePropertyChanged("extraRequestData");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(echoedScanRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(echoedSearchRetrieveRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(explainRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(scanRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(searchRetrieveRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class requestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class echoedScanRequestType : requestType {
        
        private string scanClauseField;
        
        private searchClauseType xScanClauseField;
        
        private string responsePositionField;
        
        private string maximumTermsField;
        
        private string stylesheetField;
        
        private extraDataType extraRequestDataField;
        
        public echoedScanRequestType() {
            this.responsePositionField = "1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string scanClause {
            get {
                return this.scanClauseField;
            }
            set {
                this.scanClauseField = value;
                this.RaisePropertyChanged("scanClause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public searchClauseType xScanClause {
            get {
                return this.xScanClauseField;
            }
            set {
                this.xScanClauseField = value;
                this.RaisePropertyChanged("xScanClause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=2)]
        public string responsePosition {
            get {
                return this.responsePositionField;
            }
            set {
                this.responsePositionField = value;
                this.RaisePropertyChanged("responsePosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=3)]
        public string maximumTerms {
            get {
                return this.maximumTermsField;
            }
            set {
                this.maximumTermsField = value;
                this.RaisePropertyChanged("maximumTerms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=4)]
        public string stylesheet {
            get {
                return this.stylesheetField;
            }
            set {
                this.stylesheetField = value;
                this.RaisePropertyChanged("stylesheet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public extraDataType extraRequestData {
            get {
                return this.extraRequestDataField;
            }
            set {
                this.extraRequestDataField = value;
                this.RaisePropertyChanged("extraRequestData");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/cql/xcql/")]
    public partial class searchClauseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string indexField;
        
        private relationType relationField;
        
        private string termField;
        
        /// <remarks/>
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
                this.RaisePropertyChanged("index");
            }
        }
        
        /// <remarks/>
        public relationType relation {
            get {
                return this.relationField;
            }
            set {
                this.relationField = value;
                this.RaisePropertyChanged("relation");
            }
        }
        
        /// <remarks/>
        public string term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
                this.RaisePropertyChanged("term");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/cql/xcql/")]
    public partial class relationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private modifierType[] modifiersField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("modifier", IsNullable=false)]
        public modifierType[] modifiers {
            get {
                return this.modifiersField;
            }
            set {
                this.modifiersField = value;
                this.RaisePropertyChanged("modifiers");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/cql/xcql/")]
    public partial class modifierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string comparisonField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string comparison {
            get {
                return this.comparisonField;
            }
            set {
                this.comparisonField = value;
                this.RaisePropertyChanged("comparison");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class echoedSearchRetrieveRequestType : requestType {
        
        private string queryField;
        
        private operandType xQueryField;
        
        private string startRecordField;
        
        private string maximumRecordsField;
        
        private string recordPackingField;
        
        private string recordSchemaField;
        
        private string recordXPathField;
        
        private string resultSetTTLField;
        
        private string sortKeysField;
        
        private sortKeyType[] xSortKeysField;
        
        private string stylesheetField;
        
        private extraDataType extraRequestDataField;
        
        public echoedSearchRetrieveRequestType() {
            this.startRecordField = "1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
                this.RaisePropertyChanged("query");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public operandType xQuery {
            get {
                return this.xQueryField;
            }
            set {
                this.xQueryField = value;
                this.RaisePropertyChanged("xQuery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=2)]
        public string startRecord {
            get {
                return this.startRecordField;
            }
            set {
                this.startRecordField = value;
                this.RaisePropertyChanged("startRecord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=3)]
        public string maximumRecords {
            get {
                return this.maximumRecordsField;
            }
            set {
                this.maximumRecordsField = value;
                this.RaisePropertyChanged("maximumRecords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string recordPacking {
            get {
                return this.recordPackingField;
            }
            set {
                this.recordPackingField = value;
                this.RaisePropertyChanged("recordPacking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string recordSchema {
            get {
                return this.recordSchemaField;
            }
            set {
                this.recordSchemaField = value;
                this.RaisePropertyChanged("recordSchema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string recordXPath {
            get {
                return this.recordXPathField;
            }
            set {
                this.recordXPathField = value;
                this.RaisePropertyChanged("recordXPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=7)]
        public string resultSetTTL {
            get {
                return this.resultSetTTLField;
            }
            set {
                this.resultSetTTLField = value;
                this.RaisePropertyChanged("resultSetTTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string sortKeys {
            get {
                return this.sortKeysField;
            }
            set {
                this.sortKeysField = value;
                this.RaisePropertyChanged("sortKeys");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("sortKey", IsNullable=false)]
        public sortKeyType[] xSortKeys {
            get {
                return this.xSortKeysField;
            }
            set {
                this.xSortKeysField = value;
                this.RaisePropertyChanged("xSortKeys");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=10)]
        public string stylesheet {
            get {
                return this.stylesheetField;
            }
            set {
                this.stylesheetField = value;
                this.RaisePropertyChanged("stylesheet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public extraDataType extraRequestData {
            get {
                return this.extraRequestDataField;
            }
            set {
                this.extraRequestDataField = value;
                this.RaisePropertyChanged("extraRequestData");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/cql/xcql/")]
    public partial class operandType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private prefixType[] prefixesField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("prefix", IsNullable=false)]
        public prefixType[] prefixes {
            get {
                return this.prefixesField;
            }
            set {
                this.prefixesField = value;
                this.RaisePropertyChanged("prefixes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("searchClause", typeof(searchClauseType), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("triple", typeof(tripleType), Order=1)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/cql/xcql/")]
    public partial class prefixType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string identifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("identifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/cql/xcql/")]
    public partial class tripleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private booleanType booleanField;
        
        private operandType leftOperandField;
        
        private operandType rightOperandField;
        
        /// <remarks/>
        public booleanType boolean {
            get {
                return this.booleanField;
            }
            set {
                this.booleanField = value;
                this.RaisePropertyChanged("boolean");
            }
        }
        
        /// <remarks/>
        public operandType leftOperand {
            get {
                return this.leftOperandField;
            }
            set {
                this.leftOperandField = value;
                this.RaisePropertyChanged("leftOperand");
            }
        }
        
        /// <remarks/>
        public operandType rightOperand {
            get {
                return this.rightOperandField;
            }
            set {
                this.rightOperandField = value;
                this.RaisePropertyChanged("rightOperand");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/cql/xcql/")]
    public partial class booleanType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private modifierType[] modifiersField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("modifier", IsNullable=false)]
        public modifierType[] modifiers {
            get {
                return this.modifiersField;
            }
            set {
                this.modifiersField = value;
                this.RaisePropertyChanged("modifiers");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class sortKeyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pathField;
        
        private string schemaField;
        
        private bool ascendingField;
        
        private bool ascendingFieldSpecified;
        
        private bool caseSensitiveField;
        
        private bool caseSensitiveFieldSpecified;
        
        private string missingValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string schema {
            get {
                return this.schemaField;
            }
            set {
                this.schemaField = value;
                this.RaisePropertyChanged("schema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ascending {
            get {
                return this.ascendingField;
            }
            set {
                this.ascendingField = value;
                this.RaisePropertyChanged("ascending");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ascendingSpecified {
            get {
                return this.ascendingFieldSpecified;
            }
            set {
                this.ascendingFieldSpecified = value;
                this.RaisePropertyChanged("ascendingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool caseSensitive {
            get {
                return this.caseSensitiveField;
            }
            set {
                this.caseSensitiveField = value;
                this.RaisePropertyChanged("caseSensitive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool caseSensitiveSpecified {
            get {
                return this.caseSensitiveFieldSpecified;
            }
            set {
                this.caseSensitiveFieldSpecified = value;
                this.RaisePropertyChanged("caseSensitiveSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string missingValue {
            get {
                return this.missingValueField;
            }
            set {
                this.missingValueField = value;
                this.RaisePropertyChanged("missingValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class scanRequestType : requestType {
        
        private string scanClauseField;
        
        private string responsePositionField;
        
        private string maximumTermsField;
        
        private string stylesheetField;
        
        private extraDataType extraRequestDataField;
        
        public scanRequestType() {
            this.responsePositionField = "1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string scanClause {
            get {
                return this.scanClauseField;
            }
            set {
                this.scanClauseField = value;
                this.RaisePropertyChanged("scanClause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string responsePosition {
            get {
                return this.responsePositionField;
            }
            set {
                this.responsePositionField = value;
                this.RaisePropertyChanged("responsePosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=2)]
        public string maximumTerms {
            get {
                return this.maximumTermsField;
            }
            set {
                this.maximumTermsField = value;
                this.RaisePropertyChanged("maximumTerms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=3)]
        public string stylesheet {
            get {
                return this.stylesheetField;
            }
            set {
                this.stylesheetField = value;
                this.RaisePropertyChanged("stylesheet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public extraDataType extraRequestData {
            get {
                return this.extraRequestDataField;
            }
            set {
                this.extraRequestDataField = value;
                this.RaisePropertyChanged("extraRequestData");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class scanResponseType : responseType {
        
        private termType[] termsField;
        
        private echoedScanRequestType echoedScanRequestField;
        
        private diagnosticType[] diagnosticsField;
        
        private extraDataType extraResponseDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("term", IsNullable=false)]
        public termType[] terms {
            get {
                return this.termsField;
            }
            set {
                this.termsField = value;
                this.RaisePropertyChanged("terms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public echoedScanRequestType echoedScanRequest {
            get {
                return this.echoedScanRequestField;
            }
            set {
                this.echoedScanRequestField = value;
                this.RaisePropertyChanged("echoedScanRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("diagnostic", Namespace="http://www.loc.gov/zing/srw/diagnostic/", IsNullable=false)]
        public diagnosticType[] diagnostics {
            get {
                return this.diagnosticsField;
            }
            set {
                this.diagnosticsField = value;
                this.RaisePropertyChanged("diagnostics");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public extraDataType extraResponseData {
            get {
                return this.extraResponseDataField;
            }
            set {
                this.extraResponseDataField = value;
                this.RaisePropertyChanged("extraResponseData");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.loc.gov/zing/srw/")]
    public partial class searchRetrieveResponseType : responseType {
        
        private string numberOfRecordsField;
        
        private string resultSetIdField;
        
        private string resultSetIdleTimeField;
        
        private recordType[] recordsField;
        
        private string nextRecordPositionField;
        
        private echoedSearchRetrieveRequestType echoedSearchRetrieveRequestField;
        
        private diagnosticType[] diagnosticsField;
        
        private extraDataType extraResponseDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string numberOfRecords {
            get {
                return this.numberOfRecordsField;
            }
            set {
                this.numberOfRecordsField = value;
                this.RaisePropertyChanged("numberOfRecords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultSetId {
            get {
                return this.resultSetIdField;
            }
            set {
                this.resultSetIdField = value;
                this.RaisePropertyChanged("resultSetId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=2)]
        public string resultSetIdleTime {
            get {
                return this.resultSetIdleTimeField;
            }
            set {
                this.resultSetIdleTimeField = value;
                this.RaisePropertyChanged("resultSetIdleTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("record", IsNullable=false)]
        public recordType[] records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
                this.RaisePropertyChanged("records");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=4)]
        public string nextRecordPosition {
            get {
                return this.nextRecordPositionField;
            }
            set {
                this.nextRecordPositionField = value;
                this.RaisePropertyChanged("nextRecordPosition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public echoedSearchRetrieveRequestType echoedSearchRetrieveRequest {
            get {
                return this.echoedSearchRetrieveRequestField;
            }
            set {
                this.echoedSearchRetrieveRequestField = value;
                this.RaisePropertyChanged("echoedSearchRetrieveRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("diagnostic", Namespace="http://www.loc.gov/zing/srw/diagnostic/", IsNullable=false)]
        public diagnosticType[] diagnostics {
            get {
                return this.diagnosticsField;
            }
            set {
                this.diagnosticsField = value;
                this.RaisePropertyChanged("diagnostics");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public extraDataType extraResponseData {
            get {
                return this.extraResponseDataField;
            }
            set {
                this.extraResponseDataField = value;
                this.RaisePropertyChanged("extraResponseData");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRetrieveOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.loc.gov/zing/srw/", Order=0)]
        public HistoriskAtlas.Service.ServiceReferenceBiblio.searchRetrieveRequestType searchRetrieveRequest;
        
        public SearchRetrieveOperationRequest() {
        }
        
        public SearchRetrieveOperationRequest(HistoriskAtlas.Service.ServiceReferenceBiblio.searchRetrieveRequestType searchRetrieveRequest) {
            this.searchRetrieveRequest = searchRetrieveRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRetrieveOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.loc.gov/zing/srw/", Order=0)]
        public HistoriskAtlas.Service.ServiceReferenceBiblio.searchRetrieveResponseType searchRetrieveResponse;
        
        public SearchRetrieveOperationResponse() {
        }
        
        public SearchRetrieveOperationResponse(HistoriskAtlas.Service.ServiceReferenceBiblio.searchRetrieveResponseType searchRetrieveResponse) {
            this.searchRetrieveResponse = searchRetrieveResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScanOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.loc.gov/zing/srw/", Order=0)]
        public HistoriskAtlas.Service.ServiceReferenceBiblio.scanRequestType scanRequest;
        
        public ScanOperationRequest() {
        }
        
        public ScanOperationRequest(HistoriskAtlas.Service.ServiceReferenceBiblio.scanRequestType scanRequest) {
            this.scanRequest = scanRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScanOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.loc.gov/zing/srw/", Order=0)]
        public HistoriskAtlas.Service.ServiceReferenceBiblio.scanResponseType scanResponse;
        
        public ScanOperationResponse() {
        }
        
        public ScanOperationResponse(HistoriskAtlas.Service.ServiceReferenceBiblio.scanResponseType scanResponse) {
            this.scanResponse = scanResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SRWPortChannel : HistoriskAtlas.Service.ServiceReferenceBiblio.SRWPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SRWPortClient : System.ServiceModel.ClientBase<HistoriskAtlas.Service.ServiceReferenceBiblio.SRWPort>, HistoriskAtlas.Service.ServiceReferenceBiblio.SRWPort {
        
        public SRWPortClient() {
        }
        
        public SRWPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SRWPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRWPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SRWPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HistoriskAtlas.Service.ServiceReferenceBiblio.SearchRetrieveOperationResponse HistoriskAtlas.Service.ServiceReferenceBiblio.SRWPort.SearchRetrieveOperation(HistoriskAtlas.Service.ServiceReferenceBiblio.SearchRetrieveOperationRequest request) {
            return base.Channel.SearchRetrieveOperation(request);
        }
        
        public HistoriskAtlas.Service.ServiceReferenceBiblio.searchRetrieveResponseType SearchRetrieveOperation(HistoriskAtlas.Service.ServiceReferenceBiblio.searchRetrieveRequestType searchRetrieveRequest) {
            HistoriskAtlas.Service.ServiceReferenceBiblio.SearchRetrieveOperationRequest inValue = new HistoriskAtlas.Service.ServiceReferenceBiblio.SearchRetrieveOperationRequest();
            inValue.searchRetrieveRequest = searchRetrieveRequest;
            HistoriskAtlas.Service.ServiceReferenceBiblio.SearchRetrieveOperationResponse retVal = ((HistoriskAtlas.Service.ServiceReferenceBiblio.SRWPort)(this)).SearchRetrieveOperation(inValue);
            return retVal.searchRetrieveResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HistoriskAtlas.Service.ServiceReferenceBiblio.ScanOperationResponse HistoriskAtlas.Service.ServiceReferenceBiblio.SRWPort.ScanOperation(HistoriskAtlas.Service.ServiceReferenceBiblio.ScanOperationRequest request) {
            return base.Channel.ScanOperation(request);
        }
        
        public HistoriskAtlas.Service.ServiceReferenceBiblio.scanResponseType ScanOperation(HistoriskAtlas.Service.ServiceReferenceBiblio.scanRequestType scanRequest) {
            HistoriskAtlas.Service.ServiceReferenceBiblio.ScanOperationRequest inValue = new HistoriskAtlas.Service.ServiceReferenceBiblio.ScanOperationRequest();
            inValue.scanRequest = scanRequest;
            HistoriskAtlas.Service.ServiceReferenceBiblio.ScanOperationResponse retVal = ((HistoriskAtlas.Service.ServiceReferenceBiblio.SRWPort)(this)).ScanOperation(inValue);
            return retVal.scanResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.loc.gov/zing/srw/interfaces/", ConfigurationName="ServiceReferenceBiblio.ExplainPort")]
    public interface ExplainPort {
        
        // CODEGEN: Generating message contract since the operation ExplainOperation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestType))]
        HistoriskAtlas.Service.ServiceReferenceBiblio.ExplainOperationResponse ExplainOperation(HistoriskAtlas.Service.ServiceReferenceBiblio.ExplainOperationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExplainOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.loc.gov/zing/srw/", Order=0)]
        public HistoriskAtlas.Service.ServiceReferenceBiblio.explainRequestType explainRequest;
        
        public ExplainOperationRequest() {
        }
        
        public ExplainOperationRequest(HistoriskAtlas.Service.ServiceReferenceBiblio.explainRequestType explainRequest) {
            this.explainRequest = explainRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExplainOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.loc.gov/zing/srw/", Order=0)]
        public HistoriskAtlas.Service.ServiceReferenceBiblio.explainResponseType explainResponse;
        
        public ExplainOperationResponse() {
        }
        
        public ExplainOperationResponse(HistoriskAtlas.Service.ServiceReferenceBiblio.explainResponseType explainResponse) {
            this.explainResponse = explainResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExplainPortChannel : HistoriskAtlas.Service.ServiceReferenceBiblio.ExplainPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExplainPortClient : System.ServiceModel.ClientBase<HistoriskAtlas.Service.ServiceReferenceBiblio.ExplainPort>, HistoriskAtlas.Service.ServiceReferenceBiblio.ExplainPort {
        
        public ExplainPortClient() {
        }
        
        public ExplainPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExplainPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExplainPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExplainPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HistoriskAtlas.Service.ServiceReferenceBiblio.ExplainOperationResponse HistoriskAtlas.Service.ServiceReferenceBiblio.ExplainPort.ExplainOperation(HistoriskAtlas.Service.ServiceReferenceBiblio.ExplainOperationRequest request) {
            return base.Channel.ExplainOperation(request);
        }
        
        public HistoriskAtlas.Service.ServiceReferenceBiblio.explainResponseType ExplainOperation(HistoriskAtlas.Service.ServiceReferenceBiblio.explainRequestType explainRequest) {
            HistoriskAtlas.Service.ServiceReferenceBiblio.ExplainOperationRequest inValue = new HistoriskAtlas.Service.ServiceReferenceBiblio.ExplainOperationRequest();
            inValue.explainRequest = explainRequest;
            HistoriskAtlas.Service.ServiceReferenceBiblio.ExplainOperationResponse retVal = ((HistoriskAtlas.Service.ServiceReferenceBiblio.ExplainPort)(this)).ExplainOperation(inValue);
            return retVal.explainResponse;
        }
    }
}
